#!/usr/bin/python3
#SPDX-FileCopyrightText: 2023 Mahiro Sudoh
#SPDX-License-Identifier: BSD-3-Clause
import sys
from decimal import Decimal

ans_square = 0
ans_cube = 0
ans_fourth = 0
ans_fifth = 0

for line in sys.stdin:
    try:
        num = int(line)
        ans_square += num ** 2
        ans_cube += num ** 3
        ans_fourth += num ** 4
        ans_fifth += num ** 5
    except:
        num = Decimal(line)
        ans_square += num ** 2
        ans_cube += num ** 3
        ans_fourth += num ** 4
        ans_fifth += num ** 5
    
print(num)
print(ans_square)
print(ans_cube)
print(ans_fourth)
print(ans_fifth)
